In [0]:
import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv('COVID-19.csv')

In [0]:
bins= [0,10,20,30,40,50,60,70,80,100]
labels = ['a','b','c','d','e','f','g','h','i']
Age = pd.cut(df['age'], bins=bins, labels=labels, right=False)

In [0]:
df["Age"]=Age
df=df.drop(['age'],axis=1)

In [0]:
df=pd.concat([df,pd.get_dummies(df['Age'],drop_first=True)],axis=1)

In [6]:
df = df.drop (['Age'],axis=1)
df.head()

Sno  gender  body temperature  Dry Cough  sour throat  ...  e  f  g  h  i
0    1       1              98.6          0            0  ...  0  0  0  0  0
1    2       1              99.0          1            0  ...  0  0  0  0  0
2    3       0             102.0          1            1  ...  0  1  0  0  0
3    4       0             100.0          0            0  ...  1  0  0  0  0
4    5       1              99.2          0            1  ...  0  0  0  0  0

[5 rows x 28 columns]

In [0]:
bins= [96,98.6,102,110]
labels = ['normal','fever','high fever']
Temp = pd.cut(df['body temperature'], bins=bins, labels=labels, right=False)

In [0]:
df["Temp"]=Temp
df=df.drop(['body temperature'],axis=1)

In [9]:
df=pd.concat([df,pd.get_dummies(df['Temp'],drop_first=True)],axis=1)
df = df.drop (['Temp'],axis=1)
df.head()

Sno  gender  Dry Cough  sour throat  weakness  ...  g  h  i  fever  high fever
0    1       1          0            0         0  ...  0  0  0      1           0
1    2       1          1            0         0  ...  0  0  0      1           0
2    3       0          1            1         1  ...  0  0  0      0           1
3    4       0          0            0         0  ...  0  0  0      1           0
4    5       1          0            1         0  ...  0  0  0      1           0

[5 rows x 29 columns]

In [0]:
x=df.drop(['Corona result' , 'Sno' ] , axis=1)

In [11]:
x.head()

gender  Dry Cough  sour throat  weakness  ...  h  i  fever  high fever
0       1          0            0         0  ...  0  0      1           0
1       1          1            0         0  ...  0  0      1           0
2       0          1            1         1  ...  0  0      0           1
3       0          0            0         0  ...  0  0      1           0
4       1          0            1         0  ...  0  0      1           0

[5 rows x 27 columns]

In [0]:
y=df['Corona result']

In [0]:
y1 = pd.get_dummies(y)

In [14]:
from keras.models import Sequential
model = Sequential()
from keras.layers import Dense
model.add(Dense(units=120 , input_shape=(27,),activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=50 ,activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=20 , activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=60 , activation='relu',kernel_initializer='glorot_uniform'))
model.add(Dense(units=3 , activation='softmax'))
model.summary()
from keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.001),  
              loss='categorical_crossentropy',
             metrics=['accuracy'] )
model.fit(x,y1, epochs=90)

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 120)               3360      
_________________________________________________________________
dense_2 (Dense)              (None, 50)                6050      
_________________________________________________________________
dense_3 (Dense)              (None, 20)                1020      
_________________________________________________________________
dense_4 (Dense)              (None, 60)                1260      
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 183       
Total params: 11,873
Trainable params: 11,873
Non-trainable params: 0
_________________________________________________________________
Epoch 1/90
127/127 [==============================] - 0s 1ms/step - loss: 1.0915 - accuracy: 0.3701
Epoch 2/90
127/1

In [0]:
model.save('updatemodel99-01.h5')

In [0]:
y_pred=[]
for i in range(len(x)):
  m=model.predict(x[:][i:i+1])
  m=list(m[0])
  m = m.index(max(m))
  y_pred.append(m)

In [17]:
type(y_pred)

list

In [0]:
y_testf = list(y)

In [19]:
from sklearn.metrics import confusion_matrix , accuracy_score

print(confusion_matrix(y_testf,y_pred))
print(accuracy_score(y_testf,y_pred))

[[33  0  0]
 [ 1 67  1]
 [ 0  0 25]]
0.984251968503937
